# Generated by Django 4.2.10 on 2025-05-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="queryhistory",
            name="doc_type",
            field=models.CharField(
                blank=True, help_text="Type of document queried", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="queryhistory",
            name="processing_time",
            field=models.FloatField(
                blank=True, help_text="Query processing time in seconds", null=True
            ),
        ),
    ]
