# Generated by Django 4.2.10 on 2025-05-26 09:25

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_queryhistory_doc_type_queryhistory_processing_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="GraphCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "centroid_embedding",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), null=True, size=1536
                    ),
                ),
                ("properties", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="KnowledgeNode",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "node_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("label", models.CharField(max_length=500)),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("concept", "Concept"),
                            ("author", "Author"),
                            ("method", "Method"),
                            ("finding", "Finding"),
                            ("protocol", "Protocol"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("properties", models.JSONField(default=dict)),
                (
                    "embedding",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), null=True, size=1536
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KnowledgeEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "edge_type",
                    models.CharField(
                        choices=[
                            ("cites", "Cites"),
                            ("uses", "Uses Method"),
                            ("contradicts", "Contradicts"),
                            ("supports", "Supports"),
                            ("extends", "Extends"),
                            ("authored_by", "Authored By"),
                            ("related_to", "Related To"),
                            ("derived_from", "Derived From"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("weight", models.FloatField(default=1.0)),
                ("properties", models.JSONField(default=dict)),
                (
                    "discovered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("confidence", models.FloatField(default=1.0)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="api.knowledgenode",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="api.knowledgenode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GraphUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "update_type",
                    models.CharField(
                        choices=[
                            ("node_added", "Node Added"),
                            ("edge_added", "Edge Added"),
                            ("cluster_formed", "Cluster Formed"),
                            ("insight_generated", "Insight Generated"),
                        ],
                        max_length=50,
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "cluster",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.graphcluster",
                    ),
                ),
                (
                    "edge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.knowledgeedge",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.knowledgenode",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="graphcluster",
            name="nodes",
            field=models.ManyToManyField(
                related_name="clusters", to="api.knowledgenode"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgenode",
            index=models.Index(
                fields=["node_type", "created_at"],
                name="api_knowled_node_ty_b8924b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeedge",
            index=models.Index(
                fields=["edge_type", "weight"], name="api_knowled_edge_ty_3af4e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeedge",
            index=models.Index(
                fields=["discovered_at"], name="api_knowled_discove_d01270_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="knowledgeedge",
            unique_together={("source", "target", "edge_type")},
        ),
    ]
