# Generated by Django 4.2.10 on 2025-06-18 10:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_chatsession_chatmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitoredPaper",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("authors", models.TextField()),
                ("abstract", models.TextField()),
                (
                    "doi",
                    models.CharField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                ("url", models.URLField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("biorxiv", "bioRxiv"),
                            ("research_square", "Research Square"),
                            ("pubmed", "PubMed"),
                            ("arxiv", "arXiv"),
                            ("manual", "Manual Entry"),
                        ],
                        max_length=50,
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("published_date", models.DateTimeField()),
                (
                    "discovered_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("relevance_score", models.FloatField(default=0)),
                (
                    "relevance_category",
                    models.CharField(
                        choices=[
                            ("urgent", "Urgent - Immediate attention"),
                            ("relevant", "Relevant - Weekly digest"),
                            ("monitoring", "Monitoring - Low priority"),
                            ("archived", "Archived - Processed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("relevance_reasons", models.JSONField(default=list)),
                ("smart_summary", models.TextField(blank=True)),
                ("experiment_suggestions", models.TextField(blank=True)),
                ("key_findings", models.JSONField(default=list)),
                ("is_ingested", models.BooleanField(default=False)),
                ("is_notified", models.BooleanField(default=False)),
                ("clicked_count", models.IntegerField(default=0)),
                ("flagged_by", models.JSONField(default=list)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-relevance_score", "-published_date"],
            },
        ),
        migrations.CreateModel(
            name="PaperKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=100, unique=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("urgent", "Urgent - Triggers immediate alerts"),
                            ("high", "High - Important for research"),
                            ("medium", "Medium - General interest"),
                            ("low", "Low - Background monitoring"),
                        ],
                        max_length=10,
                    ),
                ),
                ("score_boost", models.IntegerField(default=10)),
                ("created_by", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-priority", "keyword"],
            },
        ),
        migrations.CreateModel(
            name="PaperNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("slack", "Slack"),
                            ("whatsapp", "WhatsApp"),
                            ("web", "Web Dashboard"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("recipient", models.CharField(max_length=200)),
                ("is_successful", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="api.monitoredpaper",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
        migrations.AddIndex(
            model_name="monitoredpaper",
            index=models.Index(
                fields=["relevance_category", "is_notified"],
                name="api_monitor_relevan_b2e6b6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monitoredpaper",
            index=models.Index(
                fields=["published_date"], name="api_monitor_publish_640afd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monitoredpaper",
            index=models.Index(fields=["doi"], name="api_monitor_doi_1981af_idx"),
        ),
    ]
