# Generated by Django 4.2.10 on 2025-06-27 11:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_add_paper_monitoring"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="graphcluster",
            name="nodes",
        ),
        migrations.RemoveField(
            model_name="graphupdate",
            name="cluster",
        ),
        migrations.RemoveField(
            model_name="graphupdate",
            name="edge",
        ),
        migrations.RemoveField(
            model_name="graphupdate",
            name="node",
        ),
        migrations.AlterUniqueTogether(
            name="knowledgeedge",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="knowledgeedge",
            name="source",
        ),
        migrations.RemoveField(
            model_name="knowledgeedge",
            name="target",
        ),
        migrations.RemoveField(
            model_name="knowledgenode",
            name="document",
        ),
        migrations.DeleteModel(
            name="PaperKeyword",
        ),
        migrations.RemoveField(
            model_name="papernotification",
            name="paper",
        ),
        migrations.DeleteModel(
            name="GraphCluster",
        ),
        migrations.DeleteModel(
            name="GraphUpdate",
        ),
        migrations.DeleteModel(
            name="KnowledgeEdge",
        ),
        migrations.DeleteModel(
            name="KnowledgeNode",
        ),
        migrations.DeleteModel(
            name="MonitoredPaper",
        ),
        migrations.DeleteModel(
            name="PaperNotification",
        ),
    ]
