web: python manage.py migrate && python manage.py collectstatic --noinput && gunicorn rna_backend.wsgi:application --bind 0.0.0.0:$PORT
worker: celery -A rna_backend worker -l info
beat: celery -A rna_backend beat -l info