# Generated by Django 4.2.10 on 2025-06-27 10:12

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("api_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Username stored separately for audit trail integrity",
                        max_length=150,
                    ),
                ),
                (
                    "user_role",
                    models.CharField(
                        help_text="User role at the time of action", max_length=20
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN_SUCCESS", "Login Success"),
                            ("LOGIN_FAILED", "Login Failed"),
                            ("LOGOUT", "Logout"),
                            ("PASSWORD_CHANGED", "Password Changed"),
                            ("ACCOUNT_LOCKED", "Account Locked"),
                            ("ACCOUNT_UNLOCKED", "Account Unlocked"),
                            ("QUERY", "Query Executed"),
                            ("DOCUMENT_VIEWED", "Document Viewed"),
                            ("DOCUMENT_UPLOADED", "Document Uploaded"),
                            ("DOCUMENT_DELETED", "Document Deleted"),
                            ("DATA_EXPORTED", "Data Exported"),
                            ("PERMISSION_DENIED", "Permission Denied"),
                            ("ROLE_CHANGED", "User Role Changed"),
                            ("USER_CREATED", "User Created"),
                            ("USER_UPDATED", "User Updated"),
                            ("USER_DELETED", "User Deleted"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                (
                    "resource",
                    models.CharField(
                        blank=True,
                        help_text="Resource being accessed (e.g., document ID, query)",
                        max_length=255,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        default=dict, help_text="Additional details about the action"
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=True, help_text="Whether the action was successful"
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        help_text="Session ID for tracking user sessions",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrator"),
                            ("PI", "Principal Investigator"),
                            ("SENIOR_RESEARCHER", "Senior Researcher"),
                            ("RESEARCHER", "Researcher"),
                            ("GUEST", "Guest Researcher"),
                        ],
                        default="RESEARCHER",
                        help_text="User's role determining their permissions",
                        max_length=20,
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        help_text="CSIR-IGIB employee ID", max_length=50, unique=True
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        default="RNA Biology Lab",
                        help_text="Department or research group",
                        max_length=100,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Contact phone number", max_length=15
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        blank=True,
                        help_text="Official designation/title",
                        max_length=100,
                    ),
                ),
                (
                    "last_password_change",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Last password change timestamp",
                    ),
                ),
                (
                    "password_history",
                    models.JSONField(
                        default=list,
                        help_text="History of password hashes for preventing reuse",
                    ),
                ),
                (
                    "failed_login_attempts",
                    models.IntegerField(
                        default=0,
                        help_text="Number of consecutive failed login attempts",
                    ),
                ),
                (
                    "account_locked_until",
                    models.DateTimeField(
                        blank=True, help_text="Account lockout expiry time", null=True
                    ),
                ),
                (
                    "terms_accepted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When user accepted terms and conditions",
                        null=True,
                    ),
                ),
                (
                    "data_access_agreement_signed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user signed data access agreement",
                    ),
                ),
                (
                    "training_completed",
                    models.JSONField(
                        default=dict, help_text="Training modules completed with dates"
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        auto_now=True, help_text="Last activity timestamp"
                    ),
                ),
                (
                    "total_queries",
                    models.IntegerField(
                        default=0, help_text="Total number of queries made"
                    ),
                ),
                (
                    "total_documents_uploaded",
                    models.IntegerField(
                        default=0, help_text="Total documents uploaded by user"
                    ),
                ),
                (
                    "notification_preferences",
                    models.JSONField(
                        default=dict, help_text="User notification preferences"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Administrative notes about the user"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who created this user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_users",
                        to="api_auth.user",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="rna_users",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="rna_users",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
                "ordering": ["-date_joined"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="userpermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="userpermission",
            name="granted_by",
        ),
        migrations.RemoveField(
            model_name="userpermission",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="userrole",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="userrole",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="userrole",
            name="user",
        ),
        migrations.DeleteModel(
            name="AccessAttempt",
        ),
        migrations.DeleteModel(
            name="UserPermission",
        ),
        migrations.DeleteModel(
            name="UserRole",
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="api_auth.user",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["employee_id"], name="users_employe_55e465_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="users_role_0ace22_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["-last_activity"], name="users_last_ac_be241a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["-timestamp"], name="audit_logs_timesta_e93820_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "-timestamp"], name="audit_logs_user_id_e11c73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "-timestamp"], name="audit_logs_action_f48619_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["ip_address", "-timestamp"],
                name="audit_logs_ip_addr_345630_idx",
            ),
        ),
    ]
