# Generated by Django 4.2.10 on 2025-05-18 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api_analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WAFAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attack_type",
                    models.CharField(
                        choices=[
                            ("sql_injection", "SQL Injection"),
                            ("xss", "Cross-Site Scripting"),
                            ("csrf", "Cross-Site Request Forgery"),
                            ("lfi", "Local File Inclusion"),
                            ("command_injection", "Command Injection"),
                            ("path_traversal", "Path Traversal"),
                            ("ip_reputation", "IP Reputation"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("request_path", models.CharField(max_length=255)),
                ("request_method", models.CharField(max_length=10)),
                ("matched_pattern", models.CharField(blank=True, max_length=255)),
                (
                    "action_taken",
                    models.CharField(
                        choices=[
                            ("block", "Blocked"),
                            ("alert", "Alert Only"),
                            ("challenge", "Challenged User"),
                            ("log", "Logged Only"),
                        ],
                        max_length=20,
                    ),
                ),
                ("request_details", models.JSONField(blank=True, default=dict)),
                ("is_false_positive", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "related_security_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api_analytics.securityevent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["attack_type"], name="api_securit_attack__dc69e1_idx"
                    ),
                    models.Index(
                        fields=["severity"], name="api_securit_severit_633273_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="api_securit_timesta_eb8143_idx"
                    ),
                    models.Index(
                        fields=["ip_address"], name="api_securit_ip_addr_456e00_idx"
                    ),
                    models.Index(
                        fields=["action_taken"], name="api_securit_action__dd0cf3_idx"
                    ),
                    models.Index(
                        fields=["is_false_positive"],
                        name="api_securit_is_fals_adcf79_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scan_type",
                    models.CharField(
                        choices=[
                            ("vulnerability", "Vulnerability Scan"),
                            ("penetration", "Penetration Test"),
                            ("compliance", "Compliance Audit"),
                            ("code", "Code Security Review"),
                            ("config", "Configuration Review"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("tool", models.CharField(blank=True, max_length=100)),
                ("summary", models.TextField(blank=True)),
                ("high_severity_findings", models.PositiveSmallIntegerField(default=0)),
                (
                    "medium_severity_findings",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("low_severity_findings", models.PositiveSmallIntegerField(default=0)),
                ("results", models.JSONField(blank=True, default=dict)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["scan_type"], name="api_securit_scan_ty_a897e7_idx"
                    ),
                    models.Index(
                        fields=["status"], name="api_securit_status_d5d46a_idx"
                    ),
                    models.Index(
                        fields=["started_at"], name="api_securit_started_48a132_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("breach", "Data Breach"),
                            ("attack", "Attack"),
                            ("misconfiguration", "Security Misconfiguration"),
                            ("insider", "Insider Threat"),
                            ("compliance", "Compliance Violation"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("detected", "Detected"),
                            ("investigating", "Under Investigation"),
                            ("contained", "Contained"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="detected",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("affected_systems", models.TextField(blank=True)),
                ("description", models.TextField()),
                ("response_actions", models.TextField(blank=True)),
                ("root_cause_analysis", models.TextField(blank=True)),
                ("prevention_measures", models.TextField(blank=True)),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(
                        fields=["incident_type"], name="api_securit_inciden_0ea9ff_idx"
                    ),
                    models.Index(
                        fields=["status"], name="api_securit_status_932c99_idx"
                    ),
                    models.Index(
                        fields=["severity"], name="api_securit_severit_05bf81_idx"
                    ),
                    models.Index(
                        fields=["detected_at"], name="api_securit_detecte_ae8a6f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "configuration_type",
                    models.CharField(
                        choices=[
                            ("rate_limit", "Rate Limiting"),
                            ("waf", "Web Application Firewall"),
                            ("authentication", "Authentication"),
                            ("authorization", "Authorization"),
                            ("encryption", "Encryption"),
                            ("network", "Network Security"),
                            ("headers", "Security Headers"),
                        ],
                        max_length=50,
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField()),
                ("changed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("description", models.TextField(blank=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["configuration_type"],
                        name="api_securit_configu_374ac3_idx",
                    ),
                    models.Index(fields=["key"], name="api_securit_key_bf8b66_idx"),
                    models.Index(
                        fields=["changed_at"], name="api_securit_changed_3ef457_idx"
                    ),
                    models.Index(
                        fields=["changed_by"], name="api_securit_changed_992319_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BlockedIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("rate_limit", "Rate Limit Exceeded"),
                            ("suspicious", "Suspicious Activity"),
                            ("attack", "Attack Detected"),
                            ("manual", "Manually Blocked"),
                            ("brute_force", "Brute Force Attempt"),
                        ],
                        max_length=50,
                    ),
                ),
                ("blocked_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("blocked_until", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("is_permanent", models.BooleanField(default=False)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "blocked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blocked_ips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-blocked_at"],
                "indexes": [
                    models.Index(
                        fields=["ip_address"], name="api_securit_ip_addr_cf0e0a_idx"
                    ),
                    models.Index(
                        fields=["reason"], name="api_securit_reason_738c39_idx"
                    ),
                    models.Index(
                        fields=["blocked_at"], name="api_securit_blocked_91880b_idx"
                    ),
                    models.Index(
                        fields=["is_permanent"], name="api_securit_is_perm_e5e097_idx"
                    ),
                ],
            },
        ),
    ]
